### ISSUE TITLE
1.20.6 Crashing on Launch

### ISSUE THREAD

**Issue by oliveburger22** [nad2040/Elytra-Bombing-Mod#12]
![IMG_1294](https://github.com/nad2040/Elytra-Bombing-Mod/assets/170984954/c7a04874-59b6-4259-8ebe-2dad169bbf79)

Might just be a personal/user error issue, but I can't get the 1.20.6 version of the mod to launch with Fabric/Sodium. Haven't been able to fix the issue by removing other mods either (including Sodium/Iris). Are there any prerequisites for this mod? I'm new to this so any help is appreciated!! Crash report is attached above.

Best regards,

**Comment by nad2040** [comment]
Did you close this issue because it works now?

For the record, I haven't tested this mod with others.

**Comment by oliveburger22** [comment]
Yes I did, sorry! It's working perfectly, my issue was I had only installed 1 out of the 2 .jar files needed for it work properly. 

Mistake on my part. Awesome mod though, thank you!!
