### ISSUE TITLE
It doesn't do anything

### ISSUE THREAD

**Issue by skunkmommy** [nad2040/Elytra-Bombing-Mod#2]
See title. I've tried many combinations and it just doesn't do anything.

**Comment by nad2040** [comment]
Hi, what minecraft version are you running this on?

**Comment by skunkmommy** [comment]
1.19.3 fabric. It shows in my mod menu, but I can't seem to make it trigger in game.

**Comment by nad2040** [comment]
Are you holding a TNT in one hand and a flint and steel in the offhand?

**Comment by nad2040** [comment]
I will look into this later. I'm busy right now.

**Comment by nad2040** [comment]
@spudpiggy I need you to give me more information about what you did. What combinations did you try?

**Comment by nad2040** [comment]
Okay, I've been testing it and it doesn't work either. What is weird is that it works in the dev environment. I am so confused right now.

**Comment by skunkmommy** [comment]
Lmk when it does work.

**Comment by nad2040** [comment]
I made some changes yesterday. Can you test if it works now? Thanks for bringing this up. I got 1300 downloads and it's been 3 months since I released the mod and it hasn't worked this entire time and no one brought it up.

**Comment by skunkmommy** [comment]
It now works when I'm using elytra, however IMO there should be an option to have it always trigger when you right click while holding TNT and flint+steel because there are other ways of flying (aircraft mods etc)
