### ISSUE TITLE
[Suggestion] Clear log clutter

### ISSUE THREAD

**Issue by Ultimushadow** [nad2040/Elytra-Bombing-Mod#7]
Hey there, great mod, works as intended, however the mod logs 7 lines every time a right click is detected midair and for some reason it's actually logging the same information twice. Could you add an option to turn this logging off? The mod works perfectly fine so I really don't need the information, and it's making the logs even harder to parse through than they normally are 😅

**Comment by nad2040** [comment]
Hey, I added just a feature in 1.1.

A elytrabombing.json file should show up in the config directory. The attribute "should_log" will be set to true by default. You can set this to false.

Let me know if there's any issues.

**Comment by Ultimushadow** [comment]
Wow quick implementation! I'll check it out tonight and let you know if I run into anything

**Comment by nad2040** [comment]
I’m going to assume everything’s good. Closing for now.

**Comment by Ultimushadow** [comment]
Ah yep, sorry! Forgot to update the report 😅
